spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3307/bezkoder_db?useSSL=false
    username: root
    password: 123456
  jpa:
    show-sql: true
    properties: 
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update